### ISSUE TITLE
Bench test fails on Odroid-XU4

### ISSUE THREAD

**Issue by AdrianChallinorOsiris** [alexflint/go-memdump#2]
Testing MemDump on non-X86 architecture. Odroid-XU4 is  Samsung Exynos5422 Cortex™-A15 2Ghz and Cortex™-A7 Octa core CPUs. Thing Rasberry PI with a bit more memory and 8 cores. 

**adrian@odroid0:~/go/src/github.com/alexflint/go-memdump/bench$** uname -a 
Linux odroid0 3.10.105 #1 SMP PREEMPT Tue Mar 28 13:17:20 UTC 2017 armv7l armv7l armv7l GNU/Linux

Distro: Ubuntu 17.10, fully updated. 

GO: V1.9 
New clean install on new clean OS. Virtually nothing on the processor software stack that is not actually essential. 

Commands executed: 
```
go get -u github.com/alexflint/go-memdump
cd /go/src/github.com/alexflint/go-memdump 
go get -d
cd bench 
go get -d 
go build 
./bench 
```
**Output**

DECODE
                 gob     3.72 MB/s      (39.8 MB in 10.70s)
                json     4.42 MB/s      (113.8 MB in 25.71s)
panic: block.dest=36 but writer is at 48

goroutine 1 [running]:
github.com/alexflint/go-memdump.(*memEncoder).Encode(0x28b8c400, 0x11c7e8, 0x105863f0, 0x0, 0x10572100, 0x0, 0xe, 0x1)
	/home/adrian/go/src/github.com/alexflint/go-memdump/serialize.go:167 +0xc14
github.com/alexflint/go-memdump.Encode(0x1d0700, 0x1442e000, 0x11c7e8, 0x105863f0, 0x1d0898, 0x10572128)
	/home/adrian/go/src/github.com/alexflint/go-memdump/single.go:22 +0xa8
main.memdumpcodec.encode(0x105863f0, 0x4, 0x4, 0x3d, 0x0, 0x0)
	/home/adrian/go/src/github.com/alexflint/go-memdump/bench/summarize.go:100 +0x40
main.(*memdumpcodec).encode(0x1f2d88, 0x105863f0, 0x1307df98, 0x4, 0x4, 0x3d, 0x0)
	<autogenerated>:1 +0x34
main.main()
	/home/adrian/go/src/github.com/alexflint/go-memdump/bench/summarize.go:127 +0x3f8

Error occurs doing: 
 ```
             if cur.dest != uintptr(e.w.offset) {
			panic(fmt.Sprintf("block.dest=%d but writer is at %d", cur.dest, e.w.offset))
		}
```

**Comment by alexflint** [comment]
Thanks for the bug report. I'm afraid I probably won't be able to dig into this myself in the next few months, but I'm happy to provide advice if you're willing to debug it yourself.

What's happening here is that every object gets assigned a destination location in the file before anything is written (`cur.dest`), then later, when writing the objects, the serializer checks that the number of bytes written to the file so far (`e.w.offset`) matches the offset where the object that's about to be written was supposed to be located.

My first guess would be to look at the size computations here:
- https://github.com/alexflint/go-memdump/blob/master/serialize.go#L191
- https://github.com/alexflint/go-memdump/blob/master/serialize.go#L199
- https://github.com/alexflint/go-memdump/blob/master/serialize.go#L208

You could also try adding a test after [this line](https://github.com/alexflint/go-memdump/blob/master/serialize.go#L221) that checks that the number of bytes written matches `cur.size`.

Let me know if I can help more.
