### ISSUE TITLE
OOM Error when encoding large structure

### ISSUE THREAD

**Issue by bf** [alexflint/go-memdump#3]
Thanks for this package. When encoding a structure that results in a ~280MB memdump file my system starts swapping and somethimes the go process is killed due to running out of memory. Is there a way to work around this if my data structure keeps growing in size in the future? 

I have 16GB Ram and 5GB swap.

**Comment by alexflint** [comment]
I haven't optimized memory performance when writing. Intuitively it shouldn't be OOMing given the parameters you describe, but it does run a breadth first search and maintain a map over the objects its seen. You could try running a heap profile and see whether there are any obvious ways to improve performance.

(If you are running with the race detector on then you should definitely turn that off - makes a big difference)
